#!/bin/bash
source ./env
cd out
# Save COM calculation for pulling requires box size 2x diameter or larger, adding a little space
gmx editconf -f init.gro -o box.gro -c -box $GMXCPX_BOX_SIZE $GMXCPX_BOX_SIZE $GMXCPX_BOX_SIZE -bt cubic

