#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/env
cd $DIR/out/
# 18 nm droplet with 7 nm space (PBC)
gmx editconf -f 01_no_sol.gro -o 02_box.gro -c -box 25.0 25.0 25.0 -bt cubic
