#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/env
cd $DIR/out/
# preprocessor grompp
# ions.tpr: binary format for genion
gmx grompp -f $DIR/mdp/ions.mdp -c 04_drop.gro -p topol.top -o 05_ions.tpr
