#!/bin/bash
source ./env
cd out/
# Physiological NaCl concentration: 0.154 M
N_NACL="$(../scripts/calculate_nr_ions.py -s 04_drop.gro -c 0.154)"
echo "We have to add $N_NACL NaCl"
# Run genion and replace waters by Na+ and Cl-
cp 05_topol.top 06_topol.top
gmx genion -s 05_ions.tpr -o 06_drop_ions.gro -p 06_topol.top -np $N_NACL -nn $N_NACL<<EOF
13
EOF
