#!/bin/bash
# source environment
source ./env
# go to output directory
cd out/
# Reposition waters to center of the box
../scripts/waters_to_origin.py -s genion.gro -o restraint_coords.gro -x $GMXCPX_BOX_CENTER -y $GMXCPX_BOX_CENTER -z $GMXCPX_BOX_CENTER
# Change topology such that our modified restrained FF for water is included instead of the default
cp em.top nvt.top
# Create temporary file with new line in place
cat nvt.top | sed -e "s/#include \"amber99sb-ildn.ff\/tip3p.itp\"/#include \".\/tip3p.itp\"/" > tmp.top
# Replace the original topology with the temporary file
mv tmp.top nvt.top
# Prepare run file
gmx grompp -f nvt.mdp -r restraint_coords.gro -c em.gro -p nvt.top -o nvt.tpr
#gmx grompp -f $DIR/mdp/nvt.mdp -c em.gro -p topol.top -o nvt.tpr
