#!/bin/bash
source ./env
cd out/
cp nvt.top npt.top
# MAX COMMENT:
# I believe all information about positions and velovities should be already in the nvt.gro but we anyhow pass nvt.cpt in addition...?
# I think we are passing nvt.cpt because of precision, better ask Erik about this again...
gmx grompp -f ../mdp/nvt.mdp -r restraint_coords.gro -c nvt.gro -t nvt.cpt -p npt.top -o npt.tpr
