#!/bin/bash
source ./env
cd out/
cp npt.top sim.top
# npt.cpt allows to continue simulation from exactly the same point
# npt.gro = only positions and velocities
gmx grompp -f ../mdp/sim.mdp -c npt.gro -t npt.cpt -p sim.top -o sim.tpr
