#!/bin/bash
export LOG_FILE="./out/00_init.log"
source ./log_to_file
source ./env
# Initialise and clear output directory
rm -r out
mkdir out
# Copy files over into output directory
cp input/1ubq.pdb out/init.pdb
cp itp/*.itp out/
cp mdp/*.mdp out/
# Change wd to output directory
cd out
# Make a clean start, avoid complications: Remove waters from structure!
grep -v ^HETATM init.pdb > tmp.pdb
mv tmp.pdb init.pdb
# Create initial top and gro file
gmx pdb2gmx -f init.pdb -o init.gro -p init.top -i init.itp -water spce -ff gromos53a6 -vsite hydrogens -ignh
