#!/bin/bash
export LOG_FILE="./out/02_solvate.log"
source ./log_to_file
source ./env
cd out/
cp init.top solvate.top
# Solvate box
gmx solvate -cp box.gro -cs spc216.gro -p solvate.top -o solvate.gro
gmx editconf -f solvate.gro -o solvate.pdb
