#!/bin/bash
export LOG_FILE="./out/03_slab.log"
source ./log_to_file
source ./env
cd out/
cp solvate.top slab.top
gmx editconf -f solvate.gro -o tmp.gro -c -box $GMXCPX_BOX_A $GMXCPX_BOX_B $GMXCPX_BOX_C -bt triclinic -angles 90 90 60
gmx editconf -f tmp.gro -o slab.gro -translate 0.0 0.0 -$GMXCPX_BOX_C_HALF
rm tmp.gro
