#!/bin/bash
export LOG_FILE="./out/05_genion.log"
source ./log_to_file
source ./env
cd out/
# Physiological NaCl concentration: 0.154 M
N_NACL="$(../scripts/calculate_nr_ions.py -s slab.gro -c 0.154)"
echo "We have to add $N_NACL NaCl"
# Run genion and replace waters by Na+ and Cl-
cp genion_pre.top genion.top
gmx genion -s genion_pre.tpr -o genion.gro -p genion.top -np $N_NACL -nn $N_NACL<<EOF
13
EOF
# For visual inspection
gmx editconf -f genion.gro -o genion.pdb
