#!/bin/bash
export LOG_FILE="./out/06_em_pre.log"
source ./log_to_file
source ./env
cd out/
cp genion.top em.top
# Creates binary for minimising energy of the system
gmx grompp -f em.mdp -c genion.gro -p em.top -o em.tpr
