#!/bin/bash
export LOG_FILE="./out/07_em.log"
source ./log_to_file
source ./env
cd out
gmx mdrun -v -deffnm em
#gmx energy -f em.edr -o potential.xvg 
# For visual inspection
gmx editconf -f em.gro -o em.pdb
